### ISSUE TITLE
Ability to play from Spotify or Amazon music on Alexa

### ISSUE THREAD

**Issue by pooyasa** [espressif/esp-va-sdk#138]
Is this device able to play from Spotify or will that feature come in in the future?

**Comment by avsheth** [comment]
Hi @pooyasa SDK currently can play Amazon music (though not the github version, since that requires a whitelisted product ID from Amazon, given only to a productised version of AVS). 
We do not yet support Spotify due to technical issue (Spotify needing library of MBs in size), hence it is not planned for now too.
